### ISSUE TITLE
Question about 3RScan dataset used in the paper

### ISSUE THREAD

**Issue by Pixie8888** [ShunChengWu/MonoSSG#1]
Hi,

Thanks for this great work. I have a question about the 3RScan used in the 3D scene graph generation task. It seems that 3RScan official dataset doesn't provide the annotation for 3d semantic graph, but only provide semantic and instance annotation. Could you share how to obtain the annotation for 3d semantic graph? Thanks!

**Comment by ShunChengWu** [comment]
Please check this [script](https://github.com/WaldJohannaU/3RScan/blob/master/setup.sh)
